/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminDocumentIntegrityRouteImport } from './routes/admin/document-integrity'
import { Route as AdminEventPipelineRouteImport } from './routes/admin/event-pipeline'
import { Route as AdminSecurityEventsRouteImport } from './routes/admin/security-events'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSystemHealthRouteImport } from './routes/admin/system-health'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentIntegrityRoute = AdminDocumentIntegrityRouteImport.update({
  id: '/document-integrity',
  path: '/document-integrity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventPipelineRoute = AdminEventPipelineRouteImport.update({
  id: '/event-pipeline',
  path: '/event-pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityEventsRoute = AdminSecurityEventsRouteImport.update({
  id: '/security-events',
  path: '/security-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/upload': typeof UploadRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/document-integrity': typeof AdminDocumentIntegrityRoute
  '/admin/event-pipeline': typeof AdminEventPipelineRoute
  '/admin/security-events': typeof AdminSecurityEventsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/upload': typeof UploadRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/document-integrity': typeof AdminDocumentIntegrityRoute
  '/admin/event-pipeline': typeof AdminEventPipelineRoute
  '/admin/security-events': typeof AdminSecurityEventsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/upload': typeof UploadRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/document-integrity': typeof AdminDocumentIntegrityRoute
  '/admin/event-pipeline': typeof AdminEventPipelineRoute
  '/admin/security-events': typeof AdminSecurityEventsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/records'
    | '/upload'
    | '/admin/audit-logs'
    | '/admin/document-integrity'
    | '/admin/event-pipeline'
    | '/admin/security-events'
    | '/admin/settings'
    | '/admin/system-health'
    | '/admin/users'
    | '/documents/$documentId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/records'
    | '/upload'
    | '/admin/audit-logs'
    | '/admin/document-integrity'
    | '/admin/event-pipeline'
    | '/admin/security-events'
    | '/admin/settings'
    | '/admin/system-health'
    | '/admin/users'
    | '/documents/$documentId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/records'
    | '/upload'
    | '/admin/audit-logs'
    | '/admin/document-integrity'
    | '/admin/event-pipeline'
    | '/admin/security-events'
    | '/admin/settings'
    | '/admin/system-health'
    | '/admin/users'
    | '/documents/$documentId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  UploadRoute: typeof UploadRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/document-integrity': {
      id: '/admin/document-integrity'
      path: '/document-integrity'
      fullPath: '/admin/document-integrity'
      preLoaderRoute: typeof AdminDocumentIntegrityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event-pipeline': {
      id: '/admin/event-pipeline'
      path: '/event-pipeline'
      fullPath: '/admin/event-pipeline'
      preLoaderRoute: typeof AdminEventPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-events': {
      id: '/admin/security-events'
      path: '/security-events'
      fullPath: '/admin/security-events'
      preLoaderRoute: typeof AdminSecurityEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDocumentIntegrityRoute: typeof AdminDocumentIntegrityRoute
  AdminEventPipelineRoute: typeof AdminEventPipelineRoute
  AdminSecurityEventsRoute: typeof AdminSecurityEventsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDocumentIntegrityRoute: AdminDocumentIntegrityRoute,
  AdminEventPipelineRoute: AdminEventPipelineRoute,
  AdminSecurityEventsRoute: AdminSecurityEventsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  UploadRoute: UploadRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
