"""reconcile existing schema indexes

Revision ID: 29ded4a1998d
Revises: 2b489108f8dc
Create Date: 2026-09-13 17:36:29.411273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ded4a1998d'
down_revision: Union[str, Sequence[str], None] = '2b489108f8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_case_file_pages_case_file_id'), 'case_file_pages', ['case_file_id'], unique=False)
    op.drop_index(op.f('ix_documents_case_id'), table_name='case_files')
    op.create_index(op.f('ix_case_files_case_id'), 'case_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_cases_created_by'), 'cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_document_integrity_blockchain_block_id'), 'document_integrity', ['blockchain_block_id'], unique=False)
    op.create_index(op.f('ix_entities_page_id'), 'entities', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_page_id'), table_name='entities')
    op.drop_index(op.f('ix_document_integrity_blockchain_block_id'), table_name='document_integrity')
    op.drop_index(op.f('ix_cases_created_by'), table_name='cases')
    op.drop_index(op.f('ix_case_files_case_id'), table_name='case_files')
    op.create_index(op.f('ix_documents_case_id'), 'case_files', ['case_id'], unique=False)
    op.drop_index(op.f('ix_case_file_pages_case_file_id'), table_name='case_file_pages')
    # ### end Alembic commands ###
