"""baseline current schema

Revision ID: 2b489108f8dc
Revises: 
Create Date: 2026-09-13 17:29:59.267733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b489108f8dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('LAWYER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_created_by'), 'cases', ['created_by'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_created_at'), 'security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lawyer_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_case_id'), 'calendar_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_lawyer_id'), 'calendar_events', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_at'), 'calendar_events', ['start_at'], unique=False)
    op.create_table('case_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'VERIFIED', 'INTEGRITY_FAILED', 'ERROR', name='documentstatus'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('parent_file_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['parent_file_id'], ['case_files.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_files_case_id'), 'case_files', ['case_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['case_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('blockchain_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['case_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_index'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_blockchain_blocks_document_id'), 'blockchain_blocks', ['document_id'], unique=False)
    op.create_index(op.f('ix_blockchain_blocks_user_id'), 'blockchain_blocks', ['user_id'], unique=False)
    op.create_table('case_file_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_file_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_file_id', 'page_number', name='uq_case_file_page')
    )
    op.create_index(op.f('ix_case_file_pages_case_file_id'), 'case_file_pages', ['case_file_id'], unique=False)
    op.create_table('file_processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_file_id', sa.String(length=36), nullable=False),
    sa.Column('processing_type', sa.Enum('INTEGRITY_ANCHOR', 'TEXT_EXTRACTION', 'ENTITY_EXTRACTION', name='processingtype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingjobstatus', native_enum=False, length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_processing_jobs_case_file_id'), 'file_processing_jobs', ['case_file_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['case_file_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_created_by'), 'annotations', ['created_by'], unique=False)
    op.create_index(op.f('ix_annotations_page_id'), 'annotations', ['page_id'], unique=False)
    op.create_table('document_integrity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_file_id', sa.String(length=36), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('blockchain_block_id', sa.String(length=36), nullable=True),
    sa.Column('blockchain_hash', sa.String(length=64), nullable=True),
    sa.Column('anchored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_block_id'], ['blockchain_blocks.id'], ),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_file_id')
    )
    op.create_index(op.f('ix_document_integrity_blockchain_block_id'), 'document_integrity', ['blockchain_block_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'LOCATION', 'ORGANIZATION', 'VEHICLE', 'PHONE', 'EMAIL', 'DATE', 'AADHAAR', 'BANK_ACCOUNT', 'IP_ADDRESS', 'IDENTIFIER', 'EVIDENCE', 'OTHER', name='entitytype'), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['case_file_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_page_id'), 'entities', ['page_id'], unique=False)
    op.create_table('page_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('flagged_by', sa.String(length=36), nullable=False),
    sa.Column('flag_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['case_file_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_flags_flagged_by'), 'page_flags', ['flagged_by'], unique=False)
    op.create_index(op.f('ix_page_flags_page_id'), 'page_flags', ['page_id'], unique=False)
    op.create_table('annotation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_history_annotation_id'), 'annotation_history', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotation_history_changed_by'), 'annotation_history', ['changed_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_history_changed_by'), table_name='annotation_history')
    op.drop_index(op.f('ix_annotation_history_annotation_id'), table_name='annotation_history')
    op.drop_table('annotation_history')
    op.drop_index(op.f('ix_page_flags_page_id'), table_name='page_flags')
    op.drop_index(op.f('ix_page_flags_flagged_by'), table_name='page_flags')
    op.drop_table('page_flags')
    op.drop_index(op.f('ix_entities_page_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_document_integrity_blockchain_block_id'), table_name='document_integrity')
    op.drop_table('document_integrity')
    op.drop_index(op.f('ix_annotations_page_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_created_by'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_file_processing_jobs_case_file_id'), table_name='file_processing_jobs')
    op.drop_table('file_processing_jobs')
    op.drop_index(op.f('ix_case_file_pages_case_file_id'), table_name='case_file_pages')
    op.drop_table('case_file_pages')
    op.drop_index(op.f('ix_blockchain_blocks_user_id'), table_name='blockchain_blocks')
    op.drop_index(op.f('ix_blockchain_blocks_document_id'), table_name='blockchain_blocks')
    op.drop_table('blockchain_blocks')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_case_files_case_id'), table_name='case_files')
    op.drop_table('case_files')
    op.drop_index(op.f('ix_calendar_events_start_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_lawyer_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_case_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_created_at'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_cases_created_by'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
